FROM aparcar/openwrt-sdk:base

ENV SDK_URL "https://downloads.openwrt.org/releases/17.01.6/targets/x86/64/lede-sdk-17.01.6-x86-64_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz"
ENV SDK_SUFFIX .tar.xz

RUN wget -nv $SDK_URL &&\
tar xf "$(basename $SDK_URL)" &&\
rm "$(basename $SDK_URL)" &&\
mv "$(basename $SDK_URL $SDK_SUFFIX)" /sdk

WORKDIR /sdk
